### ISSUE TITLE
Presente sem valor

### ISSUE THREAD

**Issue by bhcosta90** [devajmeireles/gifts#5]
Uma coisa que notei, foi que quando o presente não tem a cota, o mesmo não tem um valor, e comparando com outros sites, por exemplo `https://sites.icasei.com.br/julianaekhauan/pages/28430369`  todos os itens ao menos tem o valor, não seria ter esse dado também para a pessoa que vai dar esse presente?

**Comment by devajmeireles** [comment]
@bhcosta90 , Obrigado pelo feedback!

A princípio o sistema foi moldado para atender a demanda onde os presentes são dados sem estipular um valor, por exemplo: "Jogo de Panelas" - pode ser qualquer uma ao invés de uma em específico (no sentido de especificar o valor). O icasei funciona de forma diferente: para cada item ele estipula o valor que a pessoa irá receber como "presente", sem que tenha sido o presente em si.

No gifts, você pode habilitar a cota e fazer algo mais ou menos assim: "Jogo de Panelas: 5 cotas de R$ 20,00 = R$ 100,00", R$ 100,00 seria o valor total do presente. Se alguém quiser lhe dá todo, ela pode assinar as 5 cotas. Deu pra entender?

Irei analisar e pensar em algo para ver mudamos alguma coisa em prol de melhorias.

**Comment by bhcosta90** [comment]
@devajmeireles acho que pode ter uma flag se quer ou não informar o valor total, penso eu, quando um presente é por exemplo uma lua de mel que o valor é exorbitante, ai sim um esquema de cotas seria legal, porém para um jogo de panela por exemplo informar o valor seria muito bom, porque na realidade a pessoa não esta dando o presente em si, mas sim o valor né.
