### ISSUE TITLE
Sugestão para o README

### ISSUE THREAD

**Issue by ribafs** [devajmeireles/gifts#7]
Beleza AJ?
Gratidão por compartilhar.
Testei aqui e funciona direitinho.

Sugestão: adicionar ao README que existe o /admin, visto que não é intuitivo.

php artisan serve

http://127.0.0.1:8000/admin

**Comment by devajmeireles** [comment]
Oi, @ribafs ! Obrigado pelo report.

Você fez o setup pelo comando `php artisan setup`? Se sim, no final desse comando ele dá a URL para o `/admin/login`. Independente disso, atualizei o README com a sua sugestão: https://github.com/devajmeireles/gifts#frontend--backend
